
services:
  frontend:
    build: ./client
 
    ports: 
      - "5173:5173"
    networks:
      - hotels
    depends_on:
      - backend
  backend:
    build: ./server
    ports: 
      - "3030:3030"
    networks:
      - hotels
    volumes:
      - ./server:/app
    
networks:
  hotels:
    driver: bridge